apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-init-pv
  labels:
    name: postgres-init-pv
spec:
  storageClassName: standard
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/pv0001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-init-pvc
  labels:
    name: postgres-init-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
